name: Docker Image Deployment to Azure Web App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  DOCKER_IMAGE_NAME: 'bestbike-ghactions'
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: azure/docker-login@v1
      with:
        login-server: bootcampdemorego.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - run: |
        docker build . -t bootcampdemorego.azurecr.io/bestbike-ghactions:${{ github.sha }}
        docker push bootcampdemorego.azurecr.io/bestbike-ghactions:${{ github.sha }}
        
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'bootcampcontainer'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: 'bootcampdemorego.azurecr.io/bestbike-ghactions:${{ github.sha }}'
